
POST http://localhost:5000/blog_post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk

{
    "title":"first post",
    "content":"This is the first post",
    "user_id":11
}
###
GET http://localhost:5000/blog_post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk

###
PATCH http://localhost:5000/blog_post/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk

{
    "title":"first post Updated",
    "content":"This is the first post updatedS 2222222222222",
    "user_id":11
}
###
DELETE http://localhost:5000/blog_post/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk
