
POST  http://localhost:5000/user/signup
Content-Type: application/json

{
    "firstname":"ifeanyi O",
    "lastname":"Ukafor",
    "username":"ifymatics",
    "email":"0korie@gmail.com",
    "password":"12345"
}
###

POST http://localhost:5000/user/signin
Content-Type: application/json

{
   "username":"ifymatics",
    "password":"12345"
   
}
###
GET http://localhost:5000/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk

###
PATCH https://uvqqwd5r1d.execute-api.us-east-1.amazonaws.com/dev/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk

{
    "firstname":"ifean",
    "lastname":"Okorie"
}
###

DELETE https://uvqqwd5r1d.execute-api.us-east-1.amazonaws.com/dev/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNzMyNzQsImV4cCI6MTY5NDE4NDA3NCwiYXVkIjoiMTEiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.EuDp3eK65tPO1b_QiqAVnGdxGIGAzOA1-wquUMnmmlk

###