
POST  http://localhost:5000/user/signup
Content-Type: application/json

{
    "firstname":"ifeanyi O",
    "lastname":"Ukafor",
    "username":"ifymatics",
    "email":"0korie@gmail.com",
    "password":"12345"
}
###

POST https://uvqqwd5r1d.execute-api.us-east-1.amazonaws.com/dev/user/signin
Content-Type: application/json

{
   "username":"ifymatis",
    "password":"12345"
   
}
###
GET https://uvqqwd5r1d.execute-api.us-east-1.amazonaws.com/dev/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxMTU5OTEsImV4cCI6MTY5NDEyNjc5MSwiYXVkIjoiMTAiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.vo37IDPyIe-K_U-YGELihFD1TOUc0FUKoyWQfQG2o2w

###
PATCH https://uvqqwd5r1d.execute-api.us-east-1.amazonaws.com/dev/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxMTU5OTEsImV4cCI6MTY5NDEyNjc5MSwiYXVkIjoiMTAiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.vo37IDPyIe-K_U-YGELihFD1TOUc0FUKoyWQfQG2o2w

{
    "firstname":"ifean",
    "lastname":"Okorie"
}
###

DELETE https://uvqqwd5r1d.execute-api.us-east-1.amazonaws.com/dev/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxMTU5OTEsImV4cCI6MTY5NDEyNjc5MSwiYXVkIjoiMTAiLCJpc3MiOiJtZWRpY2FsZGVwYXJ0dXJlcyJ9.vo37IDPyIe-K_U-YGELihFD1TOUc0FUKoyWQfQG2o2w

###