org: ifymatics
app: app
service: app-1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
